version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./flask-dev/docker/app
    ports:
      - "5000:5000"
  test:
    build:
      context: .
      dockerfile: ./flask-dev/docker/test
  nginx:
    build: ./nginx-dev
    ports:
      - "80:80"
  