version: '3'
services:
  pro:
    build:
      context: .
      dockerfile: ./flask-dev/docker/product/Dockerfile
    ports:
      - "5000:5000"
  dev:
    build:
      context: .
      dockerfile: ./flask-dev/docker/app/Dockerfile
    ports:
      - "5001:5000"
  test:
    build:
      context: .
      dockerfile: ./flask-dev/docker/test/Dockerfile
    ports:
      - "5002:5000"
  nginx:
    build: ./nginx-dev
    ports:
      - "80:80"
  